# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_checkout:
      - wget
        https://raw.githubusercontent.com/uw-ssec/docker-images/main/tutorial-scipy-2024/environment.yml
    post_create_environment:
      - pip install -r requirements.txt
    post_install:
      - pip install -e ./resources
    pre_build:
      - python resources/download_data.py
      - jupyter-book config sphinx .

conda:
  environment: environment.yml
